# Config file for automatic testing at travis-ci.org

language: python

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py37-django-21
    - env: TOX_ENV=py37-django-20
  include:
    - name: "3.5 Unit Test - Django 2.1"
      python: "3.5"
      env: TOX_ENV=py35-django-21
    - name: "3.6 Unit Test - Django 2.1"
      python: "3.6"
      env: TOX_ENV=py36-django-21
    - name: "3.7 Unit Test - Django 2.1"
      python: "3.7"
      env: TOX_ENV=py37-django-21
    - name: "3.4 Unit Test - Django 2.0"
      python: "3.4"
      env: TOX_ENV=py34-django-20
    - name: "3.5 Unit Test - Django 2.0"
      python: "3.5"
      env: TOX_ENV=py35-django-20
    - name: "3.6 Unit Test - Django 2.0"
      python: "3.6"
      env: TOX_ENV=py36-django-20
    - name: "3.7 Unit Test - Django 2.0"
      python: "3.7"
      env: TOX_ENV=py37-django-20
    - name: "2.7 Unit Test - Django 1.11"
      python: "2.7"
      env: TOX_ENV=py27-django-111
    - name: "3.4 Unit Test - Django 1.11"
      python: "3.4"
      env: TOX_ENV=py34-django-111
    - name: "3.5 Unit Test - Django 1.11"
      python: "3.5"
      env: TOX_ENV=py35-django-111
    - name: "3.6 Unit Test - Django 1.11"
      python: "3.6"
      env: TOX_ENV=py36-django-111

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV
